const resetButtonChime = new Audio("assets/audio/sfx/EarthyChimes.wav")
const hiss = new Audio("assets/audio/sfx/random/alligator hiss.wav")
const ghostBreath = new Audio("assets/audio/sfx/random/Ahhhh Breath.wav")
const lightning = new Audio("assets/audio/sfx/random/lightning strike 01.wav")
const boom = new Audio("assets/audio/sfx/low end boom sweetener 01.wav")
const bellDing = new Audio("assets/audio/sfx/bell01.wav")
const rockPop1 = new Audio("assets/audio/sfx/Tongue Pop H.wav")
const rockPop2 = new Audio("assets/audio/sfx/Tongue Pop L.wav")
